### ISSUE TITLE
Login to control panel  via WHMCS not working

### ISSUE THREAD

**Issue by thegr33nhornet** [boldbesusiax/whmcs-ispconfig3#1]
Hey,
First thanks for the work on this module, 
my only problem is that the "Login to control panel" within whmcs services doesn't work, it doesn't take me to the control panel login or anything.

It works using the original module by cwispy.
Link works on the initial commit, although it doesn't automatically log the client in which I see you seem to have implemented.

Any help would be appreciated.

**Comment by boldbesusiax** [comment]
Sorry for the delayed response! 

Thank you very much for pointing this out, I will squash this issue when I get back to the office, probably later this evening or tomorrow.

**Comment by boldbesusiax** [comment]
Ok after some testing I couldn't for the life of me get it to work. I am going to look over cwispy's code and probably just implement his solution. I am setting up a Windows client to test and see if it will work properly on Windows 7+, if I can get it to work in Windows that will be acceptable for me on the thought process that a lot of people run Windows. I suspect that GNU/Linux Debian is picky about cross domain POST authentication or my tin-foil hat web browser habits are impeding something.

**Comment by thegr33nhornet** [comment]
I've also been trying to get it working with no luck, perhaps we could just display the login credentials below the login button until a solution is found?

**Comment by boldbesusiax** [comment]
For now I am going to close this bug. Applied the login code from the initial commit which opens a new window correctly but I personally feel uncomfortable revealing the username and password in the Client Area, if only for the reason that if the customer's account is compromised in WHMCS all of their hosting information is also compromised which can have serious consequences from personal experience (Like a malicious attacker creating an SMTP relay and shooting out a truckload of spam).
